runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /(.*\.(gif|png|jpg|css|js|svg|woff|ttf|woff2)(|\.map))$
  static_files: dist/\1
  upload: dist/browser/(.*)(|\.map)
  expiration: "15m"
  http_headers:
    Strict-Transport-Security: max-age=31536000; includeSubDomains
    X-Frame-Options: DENY

- url: /(.*)
  static_files: dist/browser/index.html
  upload: dist/browser/index.html
  expiration: "15m"
  http_headers:
    Strict-Transport-Security: max-age=31536000; includeSubDomains
    X-Frame-Options: DENY