runtime: nodejs8

handlers:
  - url: /
    static_files: dist/imobles/index.html
    upload: dist/imobles/index.html
    secure: always

  - url: /(.*)
    static_files: dist/imobles/\1
    upload: dist/imobles/(.*)
    secure: always
    
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    static_files: dist/imobles/index.html
    upload: dist/imobles/index.html