runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: dist/imobles/index.html
  upload: dist/imobles/index.html

- url: /(.*)
  static_files: dist/imobles/\1
  upload: dist/imobles/(.*)

- url: /(.*\.(gif|png|jpg|css|js)(|\.map))$
  static_files: dist/\1
  upload: dist/imobles/(.*)(|\.map)

- url: /(.*)
  static_files: dist/index.html
  upload: dist/imobles/index.html