runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /(.*\.(gif|png|jpg|css|js|svg|woff|ttf|woff2)(|\.map))$
  static_files: dist/browser/\1
  upload: dist/(.*)(|\.map)

- url: /(.*)
  static_files: dist/browser/index.html
  upload: dist/browser/index.html